package xyz.jpenilla.squaremap.common.bridge.verification;

import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.*;
import org.junit.jupiter.api.Test;

final class ProofFixtureTest {
  private static final Path MANIFEST=Path.of("../testdata/bridge/v1/manifest.json");
  @Test void blocksPlaceholderArtifactsWithPrerequisites(){var e=assertThrows(ProofFixture.BlockedFixtureArtifactsException.class,()->ProofFixture.load(MANIFEST));assertTrue(e.getMessage().startsWith("blocked_fixture_artifacts"));assertEquals(3,e.prerequisites().size());}
  @Test void rejectsMissingArtifact() throws Exception {Path d=Files.createTempDirectory("proof-fixture");Path m=stageManifest(d);String x=Files.readString(m).replace("paper.jar","missing.jar");Files.writeString(m,x);var e=assertThrows(IllegalArgumentException.class,()->ProofFixture.load(m));assertTrue(e.getMessage().contains("missing or unsafe paper artifact"));}
  @Test void rejectsHashMismatch() throws Exception {Path d=Files.createTempDirectory("proof-fixture");Path m=stageManifest(d);String x=Files.readString(m).replaceFirst("8cdaa308c88a17fe9aa8c12c96a09f7d3200b33c878b5b948c595c46d65c1378","0000000000000000000000000000000000000000000000000000000000000000");Files.writeString(m,x);var e=assertThrows(IllegalArgumentException.class,()->ProofFixture.load(m));assertTrue(e.getMessage().contains("SHA-256 mismatch for paper artifact"));}
  @Test void rejectsUnsupportedVersion() throws Exception {Path d=Files.createTempDirectory("proof-fixture");Path m=stageManifest(d);Files.writeString(m,Files.readString(m).replace("\"version\": 1","\"version\": 2"));var e=assertThrows(IllegalArgumentException.class,()->ProofFixture.load(m));assertEquals("unsupported fixture version: 2",e.getMessage());}
  @Test void rejectsInvalidPortTimeoutAndFractionalNumeric() throws Exception {for(String replacement:new String[]{"25575\",\"rust_http\": 18080","120000.5","6.5"}){Path d=Files.createTempDirectory("proof-fixture");Path m=stageManifest(d);String x=Files.readString(m);x=replacement.equals("120000.5")?x.replace("120000",replacement):replacement.equals("6.5")?x.replace("\"view_distance\": 6","\"view_distance\": "+replacement):x.replace("25575","25565");Files.writeString(m,unblock(x));var e=assertThrows(IllegalArgumentException.class,()->ProofFixture.load(m));assertFalse(e.getMessage().isBlank());}}
  @Test void rejectsLifecycleOrderDuplicateMissingAndNormalization() throws Exception {for(String replacement:new String[]{"[\"baseline\",\"readiness\"","[\"readiness\",\"readiness\"","[\"readiness\",\"baseline\",\"mutation\",\"churn\",\"reload\",\"cancel\",\"resume\",\"quiescence\",\"kill\",\"restart\",\"replay\",\"shutdown\"","\"normalization\": [\"not-declared\"]"}){Path d=Files.createTempDirectory("proof-fixture");Path m=stageManifest(d);String x=Files.readString(m);if(replacement.startsWith("\"normalization"))x=x.replace("\"normalization\": []",replacement);else x=x.replaceFirst("\\[\\\"readiness\\\".*?\\]",replacement+"]");Files.writeString(m,unblock(x));var e=assertThrows(IllegalArgumentException.class,()->ProofFixture.load(m));assertFalse(e.getMessage().isBlank());}}
  @Test void rejectsRootOverlapAndSymlinkAlias() throws Exception {Path d=Files.createTempDirectory("proof-fixture");Path m=stageManifest(d);String x=Files.readString(m).replace("proof-rust-output","proof-java-output/nested");Files.writeString(m,unblock(x));var overlap=assertThrows(IllegalArgumentException.class,()->ProofFixture.load(m));assertEquals("fixture roots overlap",overlap.getMessage());Path alias=d.resolve("alias");Files.createSymbolicLink(alias,d.resolve("proof-java-output"));x=Files.readString(m).replace("proof-rust-output","alias");Files.writeString(m,unblock(x));var symlink=assertThrows(IllegalArgumentException.class,()->ProofFixture.load(m));assertEquals("fixture roots overlap",symlink.getMessage());}
  @Test void loadsValidTemporaryArtifacts() throws Exception {Path d=Files.createTempDirectory("proof-fixture");Path m=stageManifest(d);ProofFixture fixture=ProofFixture.load(unblockManifest(m));assertEquals("26.2",fixture.minecraftVersion());assertEquals("paper-26.2",fixture.paper().version());assertEquals("paper.jar",fixture.paper().path().getFileName().toString());assertEquals("plugin.jar",fixture.plugin().path().getFileName().toString());assertEquals("squaremap-server",fixture.sidecar().path().getFileName().toString());assertEquals("minecraft:normal",Files.readString(fixture.worldFixture().path()).contains("\"generator\": \"minecraft:normal\"")?"minecraft:normal":"");}
  private static String unblock(String x){return x.replace("https://fill.invalid/","https://example.test/").replace("\"artifact_prerequisites\": [\n      \"provide a real Paper server jar for paper.path\",\n      \"provide a real squaremap plugin jar for plugin.path\",\n      \"provide a real squaremap sidecar executable for sidecar.path\"\n    ],","\"artifact_prerequisites\": [],");}
  private static Path stageManifest(Path d)throws Exception {Files.copy(MANIFEST,d.resolve("manifest.json"));for(String name:new String[]{"paper.jar","plugin.jar","squaremap-server"})Files.copy(Path.of("../testdata/bridge/v1/"+name),d.resolve(name));Files.copy(Path.of("../testdata/bridge/v1/world-fixture.json"),d.resolve("world-fixture.json"));return d.resolve("manifest.json");}
  private static Path unblockManifest(Path m)throws Exception {Path unlocked=m.resolveSibling("unblocked.json");Files.writeString(unlocked,unblock(Files.readString(m)));return unlocked;}
}
