[package]
name = "squaremap-protocol"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
bytes.workspace = true
crc32c.workspace = true
prost.workspace = true
tokio.workspace = true
zstd.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true

[dev-dependencies]
hex.workspace = true
