package xyz.jpenilla.squaremap.common.bridge.verification;

import com.google.gson.*;
import java.io.*;
import java.nio.file.*;
import java.security.*;
import java.util.*;
import java.util.HexFormat;

/** Immutable, fail-closed metadata for the local Paper production proof. */
public record ProofFixture(int version, Artifact paper, Artifact plugin, Artifact sidecar, String minecraftVersion,
    WorldFixture worldFixture, WorldCorpus worldCorpus, Runtime runtime, Roots roots, Ports ports, Map<String,Long> timeoutsMs,
    long quietIntervalMs, long rssIntervalMs, Map<String,Long> thresholds, List<String> scenario,
    List<String> normalization, List<String> blockedPrerequisites) {
  private static final List<String> REQUIRED=List.of("readiness","baseline","mutation","churn","reload","cancel","resume","quiescence","kill","restart","replay","second_mutation","shutdown");
  public static ProofFixture load(Path manifest)throws IOException{
    JsonObject root; try(Reader r=Files.newBufferedReader(manifest)){root=JsonParser.parseReader(r).getAsJsonObject();}catch(RuntimeException e){throw invalid("manifest is not valid JSON",e);}
    int version=integer(root,"version"); if(version!=1)throw invalid("unsupported fixture version: "+version);
    JsonObject data=object(root,"paper_fixture"); Path base=manifest.toAbsolutePath().normalize().getParent().toRealPath();
    List<String> blocked=strings(data,"artifact_prerequisites");
    JsonObject paperNode=object(data,"paper"), pluginNode=object(data,"plugin"), sidecarNode=object(data,"sidecar");
    if(isPlaceholder(paperNode)||isPlaceholder(pluginNode)||isPlaceholder(sidecarNode))throw new BlockedFixtureArtifactsException(blocked);
    JsonObject w=object(data,"world"); World world=new World(longValue(w,"seed"),string(w,"name"),positiveInt(w,"view_distance"),positiveInt(w,"simulation_distance"),string(w,"timezone"),string(w,"locale"));
    JsonObject roots=object(data,"roots"); Roots paths=new Roots(path(roots,"data"),path(roots,"java_output"),path(roots,"rust_output"),path(roots,"diagnostics")); validateRoots(base,paths);
    JsonObject r=object(data,"runtime"); String rust=string(r,"rust_toolchain"); if(!rust.matches("1\\.88\\.0"))throw invalid("unsupported rust_toolchain: "+rust);
    WorldFixture wf=worldFixture(data,base,world);
    WorldCorpus corpus=worldCorpus(data,base);
    Runtime runtime=new Runtime(string(r,"java"),string(r,"jvm"),string(r,"os"),string(r,"arch"),string(r,"server"),string(r,"command_protocol"),rust);
    Artifact paper=artifact(data,"paper",base), plugin=artifact(data,"plugin",base), sidecar=artifact(data,"sidecar",base);
    if(!Files.isExecutable(sidecar.path()))throw invalid("sidecar artifact is not executable");
    if(!string(data,"minecraft_version").equals("26.2"))throw invalid("unsupported minecraft_version: "+string(data,"minecraft_version"));
    JsonObject p=object(data,"ports"); Ports ports=ports(p); if(Set.of(ports.paper(),ports.rcon(),ports.rustHttp()).size()!=3)throw invalid("ports must not collide");
    Map<String,Long> timeouts=numberMap(object(data,"timeouts_ms"),true); long quiet=positive(data,"quiet_interval_ms"),rss=positive(data,"rss_interval_ms"); Map<String,Long> thresholds=numberMap(object(data,"thresholds"),false);
    List<String> scenario=strings(data,"scenario"); if(!scenario.equals(REQUIRED))throw invalid("scenario must exactly match the required ordered lifecycle"); List<String> norm=strings(data,"normalization"); for(String n:norm)if(!Set.of("volatile_headers","volatile_timestamps").contains(n))throw invalid("undeclared normalization: "+n);
    return new ProofFixture(version,paper,plugin,sidecar,string(data,"minecraft_version"),wf,corpus,runtime,paths,ports,timeouts,quiet,rss,thresholds,List.copyOf(scenario),List.copyOf(norm),List.copyOf(blocked));
  }
  private static WorldFixture worldFixture(JsonObject d,Path b,World world)throws IOException{JsonObject f=object(d,"world_fixture");Path p=confined(b,string(f,"path"));if(!Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS))throw invalid("missing world fixture");String h=string(f,"sha256");if(!h.matches("[0-9a-fA-F]{64}")||!sha256(p).equalsIgnoreCase(h))throw invalid("world fixture SHA-256 mismatch");try(Reader reader=Files.newBufferedReader(p)){JsonObject x=JsonParser.parseReader(reader).getAsJsonObject();if(integer(x,"version")!=1||longValue(x,"seed")!=world.seed()||!string(x,"name").equals(world.name())||!string(x,"timezone").equals(world.timezone())||!string(x,"locale").equals(world.locale())||!string(x,"generator").equals("minecraft:normal"))throw invalid("world fixture metadata mismatch");JsonArray coordinates=x.getAsJsonArray("coordinates");if(coordinates==null||coordinates.isEmpty())throw invalid("world fixture has no coordinates");}catch(JsonParseException|IllegalStateException e){throw invalid("world fixture metadata mismatch",e);}return new WorldFixture(p,h);}
  private static WorldCorpus worldCorpus(JsonObject d,Path b)throws IOException{JsonObject c=object(d,"world_corpus");Path inventory=confined(b,string(c,"inventory"));if(!Files.isRegularFile(inventory,LinkOption.NOFOLLOW_LINKS)||Files.size(inventory)==0)throw invalid("missing or empty world corpus inventory");String ih=string(c,"sha256");if(!ih.matches("[0-9a-fA-F]{64}")||!sha256(inventory).equalsIgnoreCase(ih))throw invalid("world corpus inventory SHA-256 mismatch");JsonObject x;try(Reader r=Files.newBufferedReader(inventory)){x=JsonParser.parseReader(r).getAsJsonObject();}catch(RuntimeException e){throw invalid("invalid world corpus inventory",e);}JsonArray files=x.getAsJsonArray("files");if(files==null||files.isEmpty())throw invalid("world corpus inventory has no files");boolean level=false,region=false;List<String> paths=new ArrayList<>();for(JsonElement e:files){JsonObject f=e.getAsJsonObject();String rel=string(f,"path"),h=string(f,"sha256");if(!h.matches("[0-9a-fA-F]{64}"))throw invalid("invalid world corpus SHA-256");Path p=confined(b,rel);if(!Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)||Files.size(p)==0)throw invalid("missing or empty world corpus file: "+rel);if(!sha256(p).equalsIgnoreCase(h))throw invalid("world corpus SHA-256 mismatch: "+rel);String n=rel.replace('\\','/');if(n.equals("level.dat"))level=true;if(n.matches(".*(^|/)r\\.[-0-9]+\\.[-0-9]+\\.mca$"))region=true;paths.add(rel);}if(!level||!region)throw invalid("world corpus must include level.dat and at least one region .mca");return new WorldCorpus(inventory,ih,List.copyOf(paths));}
  private static void validateArtifactFormat(String kind,Path p)throws IOException{byte[] b=Files.readAllBytes(p);if(kind.equals("paper")||kind.equals("plugin")){if(b.length<4||b[0]!='P'||b[1]!='K'||b[2]!=3||b[3]!=4)throw invalid("invalid "+kind+" artifact format");}else if(b.length<4||b[0]!=0x7f||b[1]!='E'||b[2]!='L'||b[3]!='F')throw invalid("invalid sidecar artifact format");}
  private static Ports ports(JsonObject p){return new Ports(port(p,"paper"),port(p,"rcon"),port(p,"rust_http"));}
  private static Artifact artifact(JsonObject d,String k,Path b)throws IOException{JsonObject n=object(d,k),a=object(object(d,"artifacts"),k);String top=string(n,"sha256").toLowerCase(Locale.ROOT);String h=string(a,"sha256").toLowerCase(Locale.ROOT);if(!top.equals(h))throw invalid("top-level SHA-256 disagrees with "+k+" artifact");Path p=confined(b,string(a,"path"));if(isPlaceholder(n))return new Artifact(string(n,"version"),string(n,"url"),h,p,true);if(!Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS))throw invalid("missing or unsafe "+k+" artifact: "+p);if(!h.matches("[0-9a-f]{64}")||!sha256(p).equals(h))throw invalid("SHA-256 mismatch for "+k+" artifact");validateArtifactFormat(k,p);return new Artifact(string(n,"version"),string(n,"url"),h,p,false);}
  private static boolean isPlaceholder(JsonObject n){return n.has("url")&&n.get("url").isJsonPrimitive()&&n.get("url").getAsString().contains("fill.invalid");}
  private static Path confined(Path b,String relative)throws IOException{Path p=b.resolve(relative).normalize();if(!p.startsWith(b))throw invalid("path escapes fixture root");Path root=b.toRealPath();Path cursor=p;while(cursor!=null&&!Files.exists(cursor,LinkOption.NOFOLLOW_LINKS))cursor=cursor.getParent();if(cursor!=null&&!cursor.toRealPath().startsWith(root))throw invalid("path escapes fixture root");return p;}
  private static void validateRoots(Path b,Roots r){List<Path> ps=List.of(r.data(),r.javaOutput(),r.rustOutput(),r.diagnostics());List<Path> resolved=new ArrayList<>();for(Path p:ps){if(p.isAbsolute()||p.normalize().toString().contains(".."))throw invalid("roots must be relative");resolved.add(realRoot(b,p));}Path base;try{base=b.toRealPath();}catch(IOException e){throw invalid("cannot resolve fixture base",e);}for(Path p:resolved)if(!p.startsWith(base))throw invalid("root escapes fixture base");for(int i=0;i<resolved.size();i++)for(int j=i+1;j<resolved.size();j++)if(resolved.get(i).startsWith(resolved.get(j))||resolved.get(j).startsWith(resolved.get(i)))throw invalid("fixture roots overlap");}
  private static Path realRoot(Path b,Path relative){Path p=b.resolve(relative).normalize(),cursor=p;try{while(cursor!=null&&!Files.exists(cursor,LinkOption.NOFOLLOW_LINKS))cursor=cursor.getParent();if(cursor==null)throw invalid("cannot resolve fixture root");Path real=cursor.toRealPath();Path base=b.toRealPath();if(!real.startsWith(base))throw invalid("root escapes fixture base");return real.resolve(p.subpath(cursor.getNameCount(),p.getNameCount()));}catch(IOException e){throw invalid("cannot resolve fixture root",e);}}
  private static String sha256(Path p)throws IOException{try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(p)));}catch(NoSuchAlgorithmException e){throw new AssertionError(e);}}
  private static JsonObject object(JsonObject o,String k){JsonElement e=o.get(k);if(e==null||!e.isJsonObject())throw invalid("missing object '"+k+"'");return e.getAsJsonObject();} private static String string(JsonObject o,String k){JsonElement e=o.get(k);if(e==null||!e.isJsonPrimitive()||!e.getAsJsonPrimitive().isString()||e.getAsString().isBlank())throw invalid("missing string '"+k+"'");return e.getAsString();} private static int integer(JsonObject o,String k){JsonElement e=o.get(k);if(e==null||!e.isJsonPrimitive()||!e.getAsJsonPrimitive().isNumber()||!e.getAsJsonPrimitive().getAsString().matches("-?[0-9]+"))throw invalid("missing integer '"+k+"'");try{return e.getAsInt();}catch(RuntimeException x){throw invalid("invalid integer '"+k+"'");}} private static long longValue(JsonObject o,String k){return Long.parseLong(stringNumber(o,k));} private static String stringNumber(JsonObject o,String k){JsonElement e=o.get(k);if(e==null||!e.isJsonPrimitive()||!e.getAsJsonPrimitive().isNumber())throw invalid("missing number '"+k+"'");return e.getAsString();} private static int positiveInt(JsonObject o,String k){int v=integer(o,k);if(v<=0)throw invalid("must be positive: "+k);return v;} private static long positive(JsonObject o,String k){long v=Long.parseLong(stringNumber(o,k));if(v<=0)throw invalid("must be positive: "+k);return v;} private static int port(JsonObject o,String k){int v=integer(o,k);if(v<1024||v>65535)throw invalid("invalid port: "+k);return v;} private static Path path(JsonObject o,String k){return Path.of(string(o,k));} private static List<String> strings(JsonObject o,String k){JsonElement e=o.get(k);if(e==null||!e.isJsonArray())throw invalid("missing array '"+k+"'");List<String> out=new ArrayList<>();for(JsonElement x:e.getAsJsonArray())if(!x.isJsonPrimitive()||!x.getAsJsonPrimitive().isString())throw invalid("array contains non-string: "+k);else out.add(x.getAsString());return out;} private static Map<String,Long> numberMap(JsonObject o,boolean positive){Map<String,Long> m=new LinkedHashMap<>();for(Map.Entry<String,JsonElement> e:o.entrySet()){if(!e.getValue().isJsonPrimitive()||!e.getValue().getAsJsonPrimitive().isNumber())throw invalid("non-numeric value: "+e.getKey());long v=e.getValue().getAsLong();if(positive&&v<=0)throw invalid("must be positive: "+e.getKey());if(v<0)throw invalid("must not be negative: "+e.getKey());m.put(e.getKey(),v);}return m;} private static IllegalArgumentException invalid(String m){return new IllegalArgumentException(m);} private static IllegalArgumentException invalid(String m,Throwable c){return new IllegalArgumentException(m,c);}
  public record Ports(int paper,int rcon,int rustHttp){}
  public record Artifact(String version,String url,String sha256,Path path,boolean placeholder){} public record World(long seed,String name,int viewDistance,int simulationDistance,String timezone,String locale){} public record WorldFixture(Path path,String sha256){} public record WorldCorpus(Path inventory,String sha256,List<String> files){} public record Runtime(String java,String jvm,String os,String arch,String server,String commandProtocol,String rustToolchain){} public record Roots(Path data,Path javaOutput,Path rustOutput,Path diagnostics){}
  public static final class BlockedFixtureArtifactsException extends IllegalStateException{private final List<String> prerequisites; public BlockedFixtureArtifactsException(List<String> p){super("blocked_fixture_artifacts: "+p);prerequisites=List.copyOf(p);}public List<String> prerequisites(){return prerequisites;}}
}
