package xyz.jpenilla.squaremap.common.bridge.verification;

import com.google.gson.*;
import java.io.*;
import java.nio.file.*;
import java.security.*;
import java.util.*;
import java.util.HexFormat;

/** Immutable, fail-closed metadata for the local Paper production proof. */
public record ProofFixture(int version, Artifact paper, Artifact plugin, Artifact sidecar, String minecraftVersion,
    World world, WorldFixture worldFixture, Runtime runtime, Roots roots, Ports ports, Map<String,Long> timeoutsMs,
    long quietIntervalMs, long rssIntervalMs, Map<String,Long> thresholds, List<String> scenario,
    List<String> normalization, List<String> blockedPrerequisites) {
  private static final List<String> REQUIRED=List.of("readiness","baseline","mutation","churn","reload","cancel","resume","quiescence","kill","restart","replay","second_mutation","shutdown");
  public static ProofFixture load(Path manifest)throws IOException{
    JsonObject root; try(Reader r=Files.newBufferedReader(manifest)){root=JsonParser.parseReader(r).getAsJsonObject();}catch(RuntimeException e){throw invalid("manifest is not valid JSON",e);}
    int version=integer(root,"version"); if(version!=1)throw invalid("unsupported fixture version: "+version);
    JsonObject data=object(root,"paper_fixture"); Path base=manifest.toAbsolutePath().normalize().getParent();
    Artifact paper=artifact(data,"paper",base), plugin=artifact(data,"plugin",base), sidecar=artifact(data,"sidecar",base);
    List<String> blocked=strings(data,"artifact_prerequisites"); if(paper.placeholder()||plugin.placeholder()||sidecar.placeholder())throw new BlockedFixtureArtifactsException(blocked);
    JsonObject w=object(data,"world"); World world=new World(longValue(w,"seed"),string(w,"name"),positiveInt(w,"view_distance"),positiveInt(w,"simulation_distance"),string(w,"timezone"),string(w,"locale"));
    WorldFixture wf=worldFixture(data,base); JsonObject r=object(data,"runtime"); Runtime runtime=new Runtime(string(r,"java"),string(r,"jvm"),string(r,"os"),string(r,"arch"),string(r,"server"),string(r,"command_protocol"));
    JsonObject roots=object(data,"roots"); Roots paths=new Roots(path(roots,"data"),path(roots,"java_output"),path(roots,"rust_output"),path(roots,"diagnostics")); validateRoots(base,paths);
    JsonObject p=object(data,"ports"); Ports ports=new Ports(port(p,"paper"),port(p,"rcon"),port(p,"rust_http")); if(Set.of(ports.paper(),ports.rcon(),ports.rustHttp()).size()!=3)throw invalid("ports must not collide");
    Map<String,Long> timeouts=numberMap(object(data,"timeouts_ms"),true); long quiet=positive(data,"quiet_interval_ms"),rss=positive(data,"rss_interval_ms"); Map<String,Long> thresholds=numberMap(object(data,"thresholds"),false);
    List<String> scenario=strings(data,"scenario"); if(!scenario.equals(REQUIRED))throw invalid("scenario must exactly match the required ordered lifecycle"); List<String> norm=strings(data,"normalization"); for(String n:norm)if(!Set.of("volatile_headers","volatile_timestamps").contains(n))throw invalid("undeclared normalization: "+n);
    return new ProofFixture(version,paper,plugin,sidecar,string(data,"minecraft_version"),world,wf,runtime,paths,ports,timeouts,quiet,rss,thresholds,List.copyOf(scenario),List.copyOf(norm),List.copyOf(blocked));
  }
  private static WorldFixture worldFixture(JsonObject d,Path b)throws IOException{JsonObject f=object(d,"world_fixture");Path p=b.resolve(string(f,"path")).normalize();if(!p.startsWith(b)||!Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS))throw invalid("missing world fixture");String h=string(f,"sha256");if(!h.isBlank()&&!sha256(p).equals(h))throw invalid("world fixture SHA-256 mismatch");return new WorldFixture(p,h);}
  private static Artifact artifact(JsonObject d,String k,Path b)throws IOException{JsonObject n=object(d,k),a=object(object(d,"artifacts"),k);String url=string(n,"url"),v=string(n,"version"),h=string(a,"sha256").toLowerCase(Locale.ROOT);Path p=b.resolve(string(a,"path")).normalize();if(!p.startsWith(b)||!Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS))throw invalid("missing or unsafe "+k+" artifact: "+p);if(!h.matches("[0-9a-f]{64}")||!sha256(p).equals(h))throw invalid("SHA-256 mismatch for "+k+" artifact");return new Artifact(v,url,h,p,url.contains("fill.invalid")||p.getFileName().toString().equals("hello.bin"));}
  private static void validateRoots(Path b,Roots r){List<Path> ps=List.of(r.data(),r.javaOutput(),r.rustOutput(),r.diagnostics());for(Path p:ps)if(p.isAbsolute()||p.normalize().toString().contains(".."))throw invalid("roots must be relative");for(int i=0;i<ps.size();i++)for(int j=i+1;j<ps.size();j++){Path a=b.resolve(ps.get(i)).normalize(),c=b.resolve(ps.get(j)).normalize();try{a=a.toRealPath();c=c.toRealPath();}catch(IOException ignored){}if(a.startsWith(c)||c.startsWith(a))throw invalid("fixture roots overlap");}}
  private static String sha256(Path p)throws IOException{try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(p)));}catch(NoSuchAlgorithmException e){throw new AssertionError(e);}}
  private static JsonObject object(JsonObject o,String k){JsonElement e=o.get(k);if(e==null||!e.isJsonObject())throw invalid("missing object '"+k+"'");return e.getAsJsonObject();} private static String string(JsonObject o,String k){JsonElement e=o.get(k);if(e==null||!e.isJsonPrimitive()||!e.getAsJsonPrimitive().isString()||e.getAsString().isBlank())throw invalid("missing string '"+k+"'");return e.getAsString();} private static int integer(JsonObject o,String k){try{return o.get(k).getAsInt();}catch(RuntimeException e){throw invalid("missing integer '"+k+"'");}} private static int positiveInt(JsonObject o,String k){int n=integer(o,k);if(n<=0)throw invalid(k+" must be positive");return n;} private static long longValue(JsonObject o,String k){try{return o.get(k).getAsLong();}catch(RuntimeException e){throw invalid("missing number '"+k+"'");}} private static long positive(JsonObject o,String k){long n=longValue(o,k);if(n<=0)throw invalid(k+" must be positive");return n;} private static Path path(JsonObject o,String k){String s=string(o,k);if(Path.of(s).isAbsolute()||s.contains(".."))throw invalid("root must be relative: "+k);return Path.of(s).normalize();} private static int port(JsonObject o,String k){int n=positiveInt(o,k);if(n>65535)throw invalid("invalid port");return n;} private static List<String> strings(JsonObject o,String k){JsonElement e=o.get(k);if(e==null||!e.isJsonArray())throw invalid("missing array '"+k+"'");List<String> r=new ArrayList<>();e.getAsJsonArray().forEach(x->{if(!x.isJsonPrimitive()||!x.getAsJsonPrimitive().isString()||x.getAsString().isBlank())throw invalid("invalid entry in "+k);r.add(x.getAsString());});return r;} private static Map<String,Long> numberMap(JsonObject o,boolean pos){Map<String,Long> r=new LinkedHashMap<>();o.entrySet().forEach(e->{long n;try{n=e.getValue().getAsLong();}catch(RuntimeException x){throw invalid("invalid numeric value");}if(pos?n<=0:n<0)throw invalid("invalid timing/threshold value");r.put(e.getKey(),n);});return Map.copyOf(r);} private static IllegalArgumentException invalid(String m){return new IllegalArgumentException(m);} private static IllegalArgumentException invalid(String m,Throwable t){return new IllegalArgumentException(m,t);}
  public record Artifact(String version,String url,String sha256,Path path,boolean placeholder){} public record World(long seed,String name,int viewDistance,int simulationDistance,String timezone,String locale){} public record WorldFixture(Path path,String sha256){} public record Runtime(String java,String jvm,String os,String arch,String server,String commandProtocol){} public record Roots(Path data,Path javaOutput,Path rustOutput,Path diagnostics){} public record Ports(int paper,int rcon,int rustHttp){}
  public static final class BlockedFixtureArtifactsException extends IllegalStateException{private final List<String> prerequisites; public BlockedFixtureArtifactsException(List<String> p){super("blocked_fixture_artifacts: "+p);prerequisites=List.copyOf(p);}public List<String> prerequisites(){return prerequisites;}}
}
