[workspace]
resolver = "2"
members = ["crates/squaremap-protocol", "crates/squaremap-render", "crates/squaremap-server", "crates/squaremap-state"]

[workspace.package]
edition = "2024"
rust-version = "1.88"
license = "GPL-3.0-or-later"

[workspace.dependencies]
bytes = "1.12.1"
crc32c = "0.6.8"
hex = "0.4.3"
prost = "0.14.1"
prost-build = "0.14.1"
protoc-bin-vendored = "3.2.0"
tokio = { version = "1.47.1", features = ["io-util", "macros", "rt"] }
zstd = "0.13.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
tempfile = "3.20.0"
libc = "0.2.172"
async-trait = "0.1.89"
png = "0.18.0"
